Require C++17 as a whole instead of the individual language features
tud-zih-energy/lo2s pull request #162
Opened 2020-09-07 14:49 UTC by cvonelm

As the title said.

In the meeting last friday, @tilsche and  I decided to just require C++17 as a whole instead of the different individual language features.

@bmario should probably take a look at this, because he understands CMake probably as much as a human mind is able to.

2020-09-07 15:03 UTC, tilsche commented
I was gonna press merge quietly but now that you tagged @bmario I will patiently wait until he returns.

2020-09-21 14:55 UTC, bmario requested changes

2020-09-21 14:55 UTC, bmario commented on CMakeLists.txt
> +set_property(TARGET lo2s PROPERTY CXX_STANDARD_REQUIRED ON)
```suggestion
target_compile_features(lo2s PRIVATE cxx_std_17)
```

See [this](https://cmake.org/cmake/help/v3.8/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html#prop_gbl:CMAKE_CXX_KNOWN_FEATURES)

2020-09-22 15:42 UTC, bmario approved these changes

2020-09-22 15:42 UTC, merged