Issue 198 cgroups
tud-zih-energy/lo2s pull request #199
Opened 2022-01-06 14:44 UTC by cvonelm

This adds an option to filter perf events by cgroup

@rschoene could you confirm that this does what you want it to do?

Caveats:

* This assumes that cgroupfs is mounted at /sys/fs/cgroup, where it is mounted on 99,9% of Linux systems. However there is nothing stopping you from mounting it wherever you like. Do we:
    1. Live with that
    2. Reguire full paths, which practically no other tool requires
    3. Port perfs rather ugly cgroupfs-mountpoint searching code.
* This only covers perf events, which makes sense for now (why filter x86_energy by cgroup) but we must keep that in mind for some place in the future where not everything in lo2s comes from perf (BPF for example)

2022-01-06 15:19 UTC, rschoene requested changes
Could we use getmntend() for "/proc/mounts" to get the cgroup/perf_event location?

2022-01-20 09:33 UTC, bmario reviewed
Looks good, but I'd like to see what the turtle says

2022-01-20 09:33 UTC, bmario commented on src/config.cpp
> +
A wild newline appeared

2022-01-20 09:33 UTC, bmario commented on src/config.cpp
> +                lo2s::Log::fatal() << "Can not open cgroup path /sys/fs/cgroup/"
```suggestion
                Log::fatal() << "Can not open cgroup path /sys/fs/cgroup/"
```

2022-01-20 09:33 UTC, bmario commented on src/config.cpp
> +            lo2s::Log::fatal()
```suggestion
            Log::fatal()
```

2022-02-16 15:48 UTC, cvonelm commented
I read the cgroup2 mount point from /etc/mtab now

2022-02-16 16:22 UTC, bmario requested changes

2022-02-16 16:22 UTC, bmario commented on src/config.cpp
> +        .metavar("CGROUP")
```suggestion
        .metavar("NAME")
```

2022-02-25 12:11 UTC, cvonelm commented
for cgroup (not the second version) we have to use the /proc/mounts entry that has "perf_event" as an  attribute. Implement that code.

2022-03-02 12:53 UTC, bmario requested changes

2022-03-02 12:53 UTC, bmario commented on src/config.cpp
> +            std::ifstream mtab("/proc/mounts");
the cgroup parsing should be it's own function

2022-03-02 12:53 UTC, bmario commented on src/config.cpp
> +                        config.cgroup_fd = open(cgroup_path.c_str(), O_RDONLY);
who's closing the fd?

2022-03-07 09:16 UTC, bmario commented on src/util.cpp
> +            if (cgroup_match[3].str() != "cgroup" || cgroup_match[4].str().find("perf_event"))
Should be more like `match[3] == "cgroup2" || (match[3] == cgroup && match[4] == perf_event)`

2022-03-18 15:30 UTC, merged