feat(metrics): Support heterogenous architectures with raw events
tud-zih-energy/lo2s pull request #261
Opened 2023-03-28 07:45 UTC by cvonelm

As by their nature, there is no information about which CPUs are supported for any given raw event swimming somewhere in the kernel, the only solution to get the set of supported CPUs is good old trial-and-error

2023-04-03 11:39 UTC, cvonelm commented
@tilsche can you verify that this PR has the desired effect? lo2s is able to measure the raw event now, but I can not verify if the measurement results make sense.

2023-04-03 12:13 UTC, tilsche requested changes
Works for me on the initial problem.

2023-04-03 12:13 UTC, tilsche commented on src/perf/event_provider.cpp
> +    const EventDescription test_event(ev_desc, PERF_TYPE_RAW, code, 0);
That's now unused, is it?

2023-04-04 07:07 UTC, tilsche approved these changes

2023-04-04 07:08 UTC, merged