fix(EventDescription): Turn EventDescription into real class
tud-zih-energy/lo2s pull request #276
Opened 2023-04-19 08:00 UTC by cvonelm

The current EventDescription is a mere struct with exposed struct members etc. This PR attempts to rework the EventDescription into a proper class while integrating some of the Event Handling Code into this new class.

This fixes #224 

This also fixes #275, a bug that prevents events from showing if they could only be opened with exclude_kernel=1

2023-04-27 14:03 UTC, bmario commented
I'm out of the loop about this. Can you extend the PR description (and commit message) and elaborate on what this PR tries to achieve?

2023-08-11 09:02 UTC, bmario requested changes
I really dislike, how this copies perf initialization code everywhere, but only in half of the cases. The other half has a new method as sane replacement.

2023-08-11 09:02 UTC, bmario commented on src/perf/counter/group/reader.cpp
> +        static_cast<uint32_t>(0.8 * config().mmap_pages * get_page_size());
This looks oddly familiar. :spaghetti:

2023-09-15 07:58 UTC, cvonelm commented
Dropping this PR in favour of a more thorough refactoring based on the raii-fd branch.

2023-09-15 07:58 UTC, closed without merging