Add support for parsing event names with libpfm4
tud-zih-energy/lo2s pull request #309
Opened 2023-11-15 16:01 UTC by cvonelm

libpfm4 contains information about hundreds of events for dozens of architectures. With this, a user interested in the count of retired instructions on, for example, A64Fx can now use the name "INST_RETIRED".

There are some beauty issues we have to discuss here:

libpfms event name format is hierarchical: `pmu::event:[sub event]`. in `--list-events` I currently just flatten this hierarchy:

```
  amd64_fam19h_zen3::RETIRED_SSE_AVX_FLOPS:ADD_SUB_FLOPS
  amd64_fam19h_zen3::RETIRED_SSE_AVX_FLOPS:ANY
  amd64_fam19h_zen3::RETIRED_SSE_AVX_FLOPS:DIV_FLOPS
  amd64_fam19h_zen3::RETIRED_SSE_AVX_FLOPS:MAC_FLOPS
  amd64_fam19h_zen3::RETIRED_SSE_AVX_FLOPS:MULT_FLOPS
  ```
  
  but maybe we want
  
  ```
    amd64_fam19h_zen3::RETIRED_SSE_AVX_FLOPS
                       - ADD_SUB_FLOPS
                       - ANY
                       - DIV_FLOPS
                       - MAC_FLOPS
                       - MULT_FLOPS
 ```
 or even
 ```
amd64_fam19h_zen3::
           RETIRED_SSE_AVX_FLOPS
                       - ADD_SUB_FLOPS
                       - ANY
                       - DIV_FLOPS
                       - MAC_FLOPS
                       - MULT_FLOPS
```

Also libpfm has detailed descriptionts for events. Including them in `--list-events` is probably too noisy, so may by introduce something like `--list-event-details`?

Lastly, libpfm also contains the the pre-defined perf events that we have hard-coded into lo2s, like `cache-misses` `cpu-clock` etc. Throwing our hard-coded values away is probably not an option on grounds of backwards compatibility, so maybe filter them from libpfm?

2024-07-11 09:01 UTC, bmario requested changes

2024-07-11 09:01 UTC, bmario commented on include/lo2s/perf/pfm.hpp
> +                    }
With std::optional, this could be:

```
if (auto event = pfm4_read_event(...); event) {
  events.emplace_back(std::move(*event));
}

2024-07-11 11:10 UTC, cvonelm commented on include/lo2s/perf/pfm.hpp
> +    // Use header guards ffs
I could have sworn that there were issues with double includes, but those seem to have been resolved. deleting this stuff.

2024-07-26 12:37 UTC, bmario approved these changes

2024-07-26 12:49 UTC, merged